Rails動画教材ページの実装
yanbaru-expert/team_project_40 pull request #36
Opened 2021-01-22 13:18 UTC by skaz0110

## close #15

## 実装内容
- Rails動画教材の一覧ページを作成
  - コントローラーとビューを作成 
  - ルーティングの設定
  - 動画教材一覧表示を実装

## 参考資料
  - [【公式】Bootstrap Cards](https://getbootstrap.jp/docs/4.5/components/card/)
  - [【公式】Bootstrap Grid system](https://getbootstrap.jp/docs/4.5/layout/grid/)

## チェックリスト
- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

2021-01-22 13:39 UTC, T-Tsujii requested changes

2021-01-22 13:39 UTC, T-Tsujii commented on app/views/movies/index.html.erb
> +  <% @movies.each do |movie|%>
`each.with_index` を使用すれば `count` を使わずに対応できます。

2021-01-23 05:15 UTC, skaz0110 commented on app/views/movies/index.html.erb
> +  <% @movies.each do |movie|%>
ありがとうございます！

2021-01-23 05:31 UTC, T-Tsujii requested changes
コンフリクトの解消もお願いします！

2021-01-23 05:31 UTC, T-Tsujii commented on app/views/movies/index.html.erb
> +  <% @movies.each.with_index do |movie,count|%>
引数を1にすれば `<%= count %>` でよくなります。

```suggestion
  <% @movies.each.with_index(1) do |movie,count|%>
```

2021-01-23 06:02 UTC, T-Tsujii approved these changes
LGTMです！

2021-01-23 06:02 UTC, T-Tsujii commented on config/routes.rb
> +  resources :movies, only: [:index, :show]
```suggestion
  resources :movies, only: [:index]
```

2021-01-23 09:33 UTC, riku103 approved these changes
LGTMです！

2021-01-24 07:58 UTC, merged