Railsテキスト教材一覧ページの実装
yanbaru-expert/team_project_40 pull request #40
Opened 2021-01-24 08:15 UTC by riku103

## close #17

## 実装内容
- Railsテキスト教材の一覧ページを作成
  - 画像部分はデフォルト画像のみ表示する
  - 表示するジャンルの指定と並び替え
  - ナビバーのテキスト教材ページへのリンクを設置

## 参考資料

- スタイルの調整
  - [【公式】Bootstrap Cards](https://getbootstrap.jp/docs/4.5/components/card/#%E3%82%B5%E3%82%A4%E3%82%BA(Sizing))
  - [【公式】Bootstrap Grid system](https://getbootstrap.jp/docs/4.5/layout/grid/)

## チェックリスト

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

## 備考
- 検索機能、読破済み機能は別タスクで実施
- 詳細ページへのリンク、詳細ページの作成も別タスクで実施

2021-01-24 08:40 UTC, T-Tsujii requested changes

2021-01-24 08:40 UTC, T-Tsujii commented on app/views/texts/index.html.erb
> +      <div class="col12 col-md-6 col-lg-4 mb-5">
col12ではなくcol-12ですね。

2021-01-24 12:22 UTC, T-Tsujii approved these changes
LGTMです！

2021-01-25 12:16 UTC, skaz0110 reviewed
LGTMです！

2021-01-25 12:18 UTC, skaz0110 approved these changes

2021-01-25 12:52 UTC, hirekakusi6000 commented
LGTMです！

2021-01-26 16:03 UTC, takamuu approved these changes
LGTMです！

2021-01-27 03:51 UTC, merged