チャレンジ問題集ページ実装
yanbaru-expert/team_project_40 pull request #43
Opened 2021-01-26 14:49 UTC by hirekakusi6000

close #42

## 実装内容

- rubyチャレンジ問題集ページの実装
- ヘッダーのrailsのチャレンジ問題集にリンクを実装

## チェックリスト

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

2021-01-27 04:37 UTC, T-Tsujii requested changes

2021-01-27 04:37 UTC, T-Tsujii commented on config/routes.rb
> +  get "texts/challenges" => "texts#challenges"
詳細ページもあることを考えますと，このルーティングはお勧めできません。
別にコントローラを作成した方がよいでしょう。

2021-01-27 04:37 UTC, T-Tsujii commented on app/views/texts/challenges.html.erb
> +<% challenges = ["【条件分岐】旅行プログラムを作ろう！","【メソッド】旅行プログラムを作ろう！","【クラス】ドラクエ風プログラムを作ろう！","【クラス】ToDoリストプログラムを作ろう！"] %>
こちらは暫定的な対応でしょうか。テキスト教材同様，データベースからの取得が望ましいです。
少なくともコントローラに移動した方がよいでしょう。

2021-01-27 04:37 UTC, T-Tsujii commented on app/views/texts/challenges.html.erb
> +.h2{
cssは `application.scss` もしくは，`app/assets/stylesheets` にscssファイルを作成して移動して下さい。
ただし，`h2 { }` のような他のページに影響を与える書き方，`.text1` のようなどこに使用するかが分かりづらい命名は避けて下さい。

2021-01-27 07:48 UTC, T-Tsujii requested changes

2021-01-27 07:48 UTC, T-Tsujii commented on app/views/challenges/index.html.erb
> +<%= stylesheet_link_tag "challenges", :media => "all" %>
こちらは不要です。

`application.scss` に以下が含まれているので重複します。

```
/*
 *= require_tree .
 *= require_self
 */
```

2021-01-27 07:48 UTC, T-Tsujii commented on app/assets/stylesheets/challenges.scss
> +.cards {
`.card` と混同しやすいのは避けた方がよいでしょう。

```suggestion
.text-cards { 
```

2021-01-27 07:48 UTC, T-Tsujii commented on app/assets/stylesheets/challenges.scss
> +.card {
`.card` はBootstrapで用意されたスタイルで，他でも使用する可能性があるので直接追加するのは避けましょう。

2021-01-27 07:48 UTC, T-Tsujii commented on app/views/challenges/index.html.erb
> +    <div class="card" style="width: 18rem;">
サンプル用のスタイルは消しておきましょう。

```suggestion
    <div class="card"">
```

また，可能であれば Grid System を使用して横幅次第で 3段, 2段, 1段 となるようにしてみて下さい。

https://getbootstrap.jp/docs/4.5/layout/grid/

2021-01-27 11:37 UTC, T-Tsujii requested changes

2021-01-27 11:37 UTC, T-Tsujii commented on app/views/challenges/index.html.erb
> +    <div class="col-sm-">
難しければ他の方に依頼して一旦ここを削除するか，「デベロッパーツール」もしくは「ページのソースを表示」を元アプリ（https://www.yanbaru-code.com/challenges）で使用して構造を確認してみて下さい。

2021-01-27 11:37 UTC, T-Tsujii commented on app/views/challenges/index.html.erb
> +</div>
```suggestion
```

2021-01-28 04:52 UTC, T-Tsujii requested changes

2021-01-28 04:52 UTC, T-Tsujii commented on app/views/challenges/index.html.erb
> +<div class="container">
好みもありますが，`container` は急激に横幅が短くなるので，ここは`container-fluid`を使いましょうか。

```suggestion
<div class="container-fluid">
```

2021-01-28 04:52 UTC, T-Tsujii commented on app/views/challenges/index.html.erb
> + <div class="col-12 col-md-6 col-lg-4 mb-5">
インデント幅が乱雑になっていますので，無駄な改行も含め整理して下さい。

2021-01-28 04:52 UTC, T-Tsujii commented on app/views/challenges/index.html.erb
> +        <a href="#" class="btn btn-primary">完了済みにする</a>
ボタンの横幅が中途半端ですので，長さいっぱいにしておきましょう。

```suggestion
        <a href="#" class="btn btn-primary btn-block">完了済みにする</a>

```

2021-01-28 04:52 UTC, T-Tsujii commented on config/routes.rb
> +  resources :challenges, only: [:index]
後で詳細ページが必要になりますので，追加しておいて下さい。

```suggestion
  resources :challenges, only: [:index, :show]
```

2021-02-01 10:11 UTC, T-Tsujii approved these changes
LGTMです！

2021-02-02 01:38 UTC, riku103 approved these changes
LGTMです！

コードに関してではないですが、気になる点が一点あった為、次回からで大丈夫なので対応お願いします。
1. 最新の変更が更新されてないようなので、開発中に他の方がリモートでマージしたらローカルにpullお願いします！

2021-02-02 23:25 UTC, takamuu approved these changes
LGTMです！

2021-02-03 14:17 UTC, skaz0110 approved these changes
LGTMです！

2021-02-06 14:26 UTC, merged