LINE一覧ページの実装
yanbaru-expert/team_project_40 pull request #53
Opened 2021-02-03 05:49 UTC by riku103

## close #48

## 実装内容
- lineモデルとlinesテーブルを作成
- lineページへのルーティングを設定
- DBへデータ投入
  - CSVインポート
  - `rails db:seed`で初期データの投入
- 一覧画面の実装
  - Bootstrapでスタイルの調整

## 参考資料

- CSVインポート
  - [やんばるCODE教材](https://www.yanbaru-code.com/texts/217)
- 一覧画面の実装
  - [やんばるCODE教材](https://www.yanbaru-code.com/texts/269)
- スタイルの調整
  - [Bootstrap Colors](https://getbootstrap.jp/docs/4.2/utilities/colors/)
  - [Bootstrap Tables](https://bootstrap-guide.com/content/tables)

## チェックリスト
- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

## スクリーンショット
![スクリーンショット 2021-02-03 14 47 10](https://user-images.githubusercontent.com/67620156/106704141-e9161780-662e-11eb-8a6d-2c7b73ec98f9.jpg)

## 備考
- 詳細ページは別タスクとする

2021-02-03 06:40 UTC, T-Tsujii requested changes

2021-02-03 06:40 UTC, T-Tsujii commented on app/views/layouts/_line_header.html.erb
> +<nav class="navbar navbar-expand-lg navbar-dark  bg-success">
色が異なるだけですので，新しく作成するのは避けましょう。
`controller_name` を使用してクラスを付け替えるようにしてみましょう。

2021-02-03 06:40 UTC, T-Tsujii commented on app/views/layouts/lines.html.erb
> +<!DOCTYPE html>
このファイルは使用されていませんので，削除しましょう。

2021-02-03 07:20 UTC, T-Tsujii requested changes

2021-02-03 07:20 UTC, T-Tsujii commented on app/views/layouts/_footer.html.erb
> +<% end %>
この書き方をしますとエディタがnavタグが2つあると誤解しますのでさけましょう。

```suggestion
<nav class="navbar navbar-expand-lg navbar-dark <%= ここに記述 %>">
```

の書き方で対応できます。できれば，ヘルパーにメソッドを作成し，ここで呼び出すようにするのが理想です。

2021-02-04 10:24 UTC, T-Tsujii approved these changes

2021-02-04 10:24 UTC, T-Tsujii commented on app/helpers/application_helper.rb
> +  def color
`bg_color` にしたほうがクラスの内容が分かりやすいでしょう。

```suggestion
  def bg_color
```

2021-02-04 11:47 UTC, skaz0110 approved these changes
毎回細かくコミットされてて変更が分かりやすいですね。参考になります。
LGTMです！

2021-02-04 22:47 UTC, takamuu approved these changes
LGTMです！

2021-02-07 13:45 UTC, hirekakusi6000 reviewed
LGTMです！

2021-02-07 13:45 UTC, hirekakusi6000 approved these changes
LGTMです！

2021-02-07 20:59 UTC, merged