検索機能追加
yanbaru-expert/team_project_40 pull request #55
Opened 2021-02-04 08:34 UTC by takamuu

close #44 

## 実装内容

- 検索機能追加
  - Rails6でのjquery動作設定
  - javascriputでの検索機能実装
  - Ajax実装

## 参考資料

-  [【Rails6】jQueryがなかなか使い始められない人へ](https://qiita.com/iiyama_makoto/items/940b130fd20540fd70f1)
-  [【Rails】Ajaxチュートリアル（Rails+jQuery）~処理の流れを理解しよう！](https://pikawaka.com/rails/ajax-jquery)
- [検索ボックスの値をリアルタイムに取得して、部分一致の絞込み検索を実装する](https://www.tam-tam.co.jp/tipsnote/javascript/post11315.html)
- [Bootstrap カード](https://getbootstrap.com/docs/4.4/components/card/)

## チェックリスト

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

## 備考（必要があれば）
-  Bootstrapの書式調整がやんばるCODEと微妙に違うのですが、今回調整しきれませんでした。次回以降に調整する予定です。
-  検索マークの位置と検索ボックス調整も同上。

2021-02-04 08:57 UTC, T-Tsujii requested changes

2021-02-04 08:57 UTC, T-Tsujii commented on app/javascript/packs/application.js
> +require("jquery")
この行は不要です。
（`config/webpack/environment.js` の設定で読み込めるようになっています）

```suggestion
```

2021-02-04 10:25 UTC, T-Tsujii approved these changes
LGTMです！

2021-02-04 11:42 UTC, skaz0110 approved these changes
調整については把握いたしました！
LGTMです！

2021-02-05 10:34 UTC, riku103 approved these changes
LGTMです！

2021-02-07 13:46 UTC, hirekakusi6000 approved these changes
LGTMです！

2021-02-08 07:50 UTC, merged