Line詳細ページの実装
yanbaru-expert/team_project_40 pull request #58
Opened 2021-02-08 12:55 UTC by skaz0110

## close #56 

## 実装内容
- Line詳細ページの実装
  - linesControllerのshowメソッドに記述
  - 詳細ページのViewを作成
  - 一覧ページからのリンクを別タブに飛ばすように変更

## 参考資料

- リンクを別タブで表示
  - [Qiita](https://qiita.com/Kazuhiro_Mimaki/items/b3f2d718d2bae9083290)
- bootstrapでの中央寄せ
  - [Qiita](https://qiita.com/Kazuhiro_Mimaki/items/b3f2d718d2bae9083290)

## チェックリスト
- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

2021-02-08 12:58 UTC, T-Tsujii requested changes

2021-02-08 12:58 UTC, T-Tsujii commented on app/views/lines/index.html.erb
> +        <td><%= link_to "#{line.title}", line ,target: :_blank%></td>
こちらをご覧下さい。最近のバージョンではブラウザ側で対処されつつありますが，まだ省略は早いと思います。
https://wwg.co.jp/blog/3807

2021-02-08 13:20 UTC, skaz0110 commented on app/views/lines/index.html.erb
> +        <td><%= link_to "#{line.title}", line ,target: :_blank%></td>
参考になりました。
ありがとうございます。

2021-02-08 13:21 UTC, T-Tsujii approved these changes
LGTMです！

2021-02-09 08:54 UTC, riku103 approved these changes
LGTMです！

2021-02-10 07:38 UTC, hirekakusi6000 approved these changes
LGTMです！

2021-02-14 23:28 UTC, takamuu approved these changes
LGTMです！

2021-02-15 11:19 UTC, merged