質問一覧ページの実装
yanbaru-expert/team_project_40 pull request #59
Opened 2021-02-09 12:52 UTC by hirekakusi6000

close #45

## 実装内容

- 質問一覧ページの実装
- CSVで質問一覧ページに必要なデータを取り込み
- Bootstrapによるデザイン

## 修正内容

- 未使用機能削除

## チェックリスト
- [x] GitHub で Files changed を確認
- [x] 影響し得る範囲のローカル環境での動作確認

2021-02-09 13:36 UTC, T-Tsujii requested changes

2021-02-09 13:36 UTC, T-Tsujii commented on app/controllers/questions_controller.rb
> +    @questions = Question.find(params[:id])
1件のデータですので単数形にしましょう。

```suggestion
    @question = Question.find(params[:id])
```

ところで，「質問一覧ページの実装」と記載されていますが，「詳細ページ」まで実装されるのでしょうか？

2021-02-09 13:37 UTC, T-Tsujii commented
コンフリクトの解消もしてください。

2021-02-12 10:37 UTC, T-Tsujii approved these changes
LGTMです！

2021-02-13 02:23 UTC, riku103 reviewed
初期データの投入がうまく出来ていないため、質問集一覧に表示されていません。
もう一度動作確認お願いします！

2021-02-13 02:23 UTC, riku103 commented on Gemfile
> +
不要な行は削除した方がいいかなと思います！

2021-02-13 02:23 UTC, riku103 commented on app/views/layouts/_header.html.erb
> +        　 <a class="dropdown-item" href="/questions">質問集</a>
表示が崩れてますので、インデント揃えるのをお願いします！

2021-02-13 02:23 UTC, riku103 commented on lib/autoloads/import_csv.rb
> +end
ここのendでエラーが出ています！

2021-02-28 11:07 UTC, T-Tsujii requested changes

2021-02-28 11:07 UTC, T-Tsujii commented on app/views/layouts/_header.html.erb
> +<<<<<<< HEAD
正しくコンフリクトの解消ができていません。
navタグが2つ入っています。

2021-05-07 11:33 UTC, T-Tsujii requested changes
質問一覧ページのルーティング，リンクがないようです。

2021-05-07 11:33 UTC, T-Tsujii commented on lib/autoloads/import_csv.rb
> +end
`end` が余分に入っています。

```suggestion
```

2021-05-07 11:33 UTC, T-Tsujii commented on db/seeds.rb
> +ImportCsv.movieimport('db/csv_data/question_data.csv')
`rails db:seed` 実行時にエラーが出ています。

```
ActiveRecord::RecordInvalid: バリデーションに失敗しました: Genreを入力してください, Urlを入力してください
```

2021-05-07 11:33 UTC, T-Tsujii commented on app/views/questions/show.html.erb
> +<p>Find me in app/views/questions/show.html.erb</p>
```suggestion
```

2021-05-09 07:56 UTC, T-Tsujii requested changes

2021-05-09 07:56 UTC, T-Tsujii commented on app/views/layouts/_header.html.erb
> +          Rails
ドロップメニューが開かれないようです。

2021-05-09 07:56 UTC, T-Tsujii commented on package.json
> +    "jquery": "^3.6.0",
バージョンは変更しない方がよいでしょう。

```suggestion
    "bootstrap": "^4.5.3",
    "jquery": "^3.5.1",
```

2021-05-09 07:57 UTC, T-Tsujii requested changes

2021-05-09 07:57 UTC, T-Tsujii commented on lib/autoloads/import_csv.rb
> +        title:  row["title"],
`content` が抜けています。
必要に応じて，`db/csv_data/question_data.csv` を修正しましょう。

2021-05-09 12:41 UTC, T-Tsujii approved these changes
LGTMです！

2021-05-09 13:10 UTC, merged