読破済み機能実装
yanbaru-expert/team_project_40 pull request #60
Opened 2021-02-16 06:12 UTC by takamuu

close #57 

## 実装内容

- 読破済み機能
  - Readテーブル作成
  - 多対多のモデル関連付け

## 参考資料

- [モデル関連付け　その２（多対多）](https://www.yanbaru-code.com/texts/297)

## チェックリスト

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

## スクリーンショット（必要があれば）

## 備考（必要があれば）

2021-02-16 06:31 UTC, T-Tsujii requested changes

2021-02-16 06:31 UTC, T-Tsujii commented on app/views/texts/_text.html.erb
> +              <%# <%= render "read", post: text %>
`app/views/texts/_read.html.erb` に `post` という変数はありません。 `text` ではありませんか？

2021-02-16 06:31 UTC, T-Tsujii commented on app/views/texts/_read.html.erb
> +<%= link_to '読破済みを解除', text_reads_path(@text), class: 'btn btn-primary btn-block', method: :delete, remote: true %>
`@text` を `text` にして変数を代入できるようにしましょう。
（show.html.erb も修正が必要です）

2021-02-16 07:07 UTC, T-Tsujii requested changes
詳細ページへのリンクがありませんので，別タスクで対応しなければならないですね。

2021-02-16 07:07 UTC, T-Tsujii commented on app/controllers/texts_controller.rb
> +    @text = Text.find_by(params[:id])
こちらは使用していないのではありませんか？

```suggestion
```

2021-02-16 07:07 UTC, T-Tsujii commented on app/views/texts/show.html.erb
> +  <object>
ここは`object`タグは必要ないと思います。

2021-02-16 08:32 UTC, T-Tsujii approved these changes
LGTMです！

2021-02-21 11:26 UTC, T-Tsujii requested changes

2021-02-21 11:26 UTC, T-Tsujii commented on app/assets/stylesheets/application.scss
> +  width: 350px;
iPhone SE で表示がおかしくなるので，max-widthの方がよいですよ。

```suggestion
  max-width: 350px;
```

2021-02-21 11:46 UTC, T-Tsujii approved these changes
LGTMです！

2021-02-24 01:10 UTC, riku103 approved these changes
LGTMです！

2021-02-26 05:28 UTC, skaz0110 approved these changes
LGTMです！

2021-02-28 07:49 UTC, hirekakusi6000 approved these changes
LGTMです！

2021-03-03 02:31 UTC, merged