視聴済み機能実装
yanbaru-expert/team_project_40 pull request #61
Opened 2021-03-04 07:53 UTC by takamuu

close #49 

## 実装内容

- 視聴済み機能
  - 動画教材一覧ページに視聴済み機能を実装
　  - watched_movieテーブル作成
　  - 非同期実装
  - Rails教材詳細ページへのYouTube埋め込み
    - movieテーブルへのtext_idカラム追加
    - 教材詳細ページに視聴済み機能を実装 

## 参考資料

- やんばるエキスパート
  - [YouTube動画の投稿](https://www.yanbaru-code.com/texts/349)
  - [モデルの関連付け その2（多対多）](https://www.yanbaru-code.com/texts/297)

## チェックリスト

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

## 備考

教材の詳細ページは今回未調整

2021-03-04 08:26 UTC, T-Tsujii requested changes

2021-03-04 08:26 UTC, T-Tsujii commented on app/admin/movies.rb
> +      input :text_id
movie と text に関連付けを入れておけば，次の書き方で選択式になります。

```suggestion
      input :text
```

2021-03-04 08:26 UTC, T-Tsujii commented on app/models/movie.rb
> +  has_many :users
userとは関連付いていません。

```suggestion
```

2021-03-05 11:44 UTC, T-Tsujii requested changes

2021-03-05 11:44 UTC, T-Tsujii commented on app/models/movie.rb
> +  belongs_to :text
デフォルトで `presence: true` が入るのでエラーが出ていますね。

```suggestion
  belongs_to :text, optional: true
```

2021-03-05 11:44 UTC, T-Tsujii commented on app/controllers/movies_controller.rb
> +  PER_PAGE = 10
最後列が中途半端ですので，1,2,3の公倍数である6の倍数にしておきましょう。

```suggestion
  PER_PAGE = 12
```

2021-03-05 12:13 UTC, T-Tsujii approved these changes
LGTMです！

2021-03-06 03:13 UTC, skaz0110 approved these changes
別件ですが、動画教材ページの上部に、ページタイトルの追加お願い致します。

実装についてはLGTMです！

2021-03-10 10:07 UTC, hirekakusi6000 approved these changes

2021-03-10 10:09 UTC, hirekakusi6000 approved these changes
LGTMです！

2021-03-15 12:05 UTC, riku103 approved these changes
LGTMです！

2021-03-15 12:08 UTC, merged