進捗管理機能の実装(テキスト教材)
yanbaru-expert/team_project_40 pull request #63
Opened 2021-03-17 12:25 UTC by skaz0110

## close #51 

## 実装内容

- 進捗管理機能の実装
  - ヘッダーのマイページにドロップダウンとして追加
  - マイページのコントローラーを作成
  - 進捗管理ページのルーティングを設定
  - 進捗のグラフにはBootstrapのProgressを使用

- ヘッダーの修正
  -   デザイン崩れ
  -   ロゴクリック時はトップページへ遷移

## 参考資料

- Progress
  - [Bootstrap](https://getbootstrap.jp/docs/4.4/components/progress/)
  - [Bootstrap](https://bootstrap-guide.com/components/progress)

## チェックリスト

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

2021-03-17 12:53 UTC, T-Tsujii requested changes

2021-03-17 12:53 UTC, T-Tsujii commented on app/views/mypages/index.html.erb
> +    Basic  (<%= selectUserReadCount("Basic")%>/<%=selectTextGenreCount("Basic")%>)
実装はできているのですが，かなり無駄にSQLが走っていますね。このページに入った際のターミナルを確認してみて下さい。

可能であれば，コントローラ側で必要なデータを一括で取得し，以下のような形式の配列を利用できるようにするのが理想です。

なかなか大変ですので，ここまでが難しければこのプルリクでApproveしてもよいですので，連絡いただけますか。

```
{
  Rails:
    {
      name: "Ruby on Rails",
      color: "#dc3545",
      total_count: "1/3",
      percentage: "33"
    },
  PHP: {
    ...
  }
}
```

2021-03-18 12:55 UTC, skaz0110 commented on app/views/mypages/index.html.erb
> +    Basic  (<%= selectUserReadCount("Basic")%>/<%=selectTextGenreCount("Basic")%>)
SQLまで気に掛けることができておりませんでした。勉強になります。

2021-03-18 13:01 UTC, skaz0110 reviewed
テスト

2021-03-18 13:22 UTC, T-Tsujii requested changes

2021-03-18 13:22 UTC, T-Tsujii commented on app/controllers/mypages_controller.rb
> +    @genreCount =
処理がコントローラに移動している点は悪くないのですが，SQLが複数回走っているのは変化していないですね。
`group` メソッドをうまく使えばもう少し効率よく対応できます。

難しければ，Ruby の `group_by` メソッドで妥協してもよいでしょう。

2021-03-21 12:43 UTC, skaz0110 commented on app/controllers/mypages_controller.rb
> +    @genreCount =
groupメソッドを用いて以下のように修正したのですが
読破していないジャンルが存在する場合、それらを０件として取得するにはどのようにすれば良いのでしょうか。

```
@genreCount =
    {
      userGenre: current_user.read_texts.group(:genre).count,
      allGenre:  Text.group(:genre).count()
    }
```

2021-03-21 13:43 UTC, T-Tsujii commented on app/controllers/mypages_controller.rb
> +    @genreCount =
`||` を使いましょう！

https://qiita.com/ngron/items/4d3ca9827d1969fccd60

2021-03-22 12:59 UTC, T-Tsujii approved these changes
LGTMです！

2021-03-22 12:59 UTC, T-Tsujii commented on app/controllers/mypages_controller.rb
> +      allGenre:  Text.group(:genre).count()
```suggestion
      allGenre:  Text.group(:genre).count
```

2021-03-22 14:52 UTC, hirekakusi6000 approved these changes
LGMTです！

2021-03-22 15:10 UTC, takamuu commented
LGTMです！

2021-03-24 20:27 UTC, riku103 approved these changes
LGTMです！

2021-03-25 10:38 UTC, merged